/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

 import { EcsFields } from '../types/'

 export const ecsFields: EcsFields = {
   '@timestamp': {
     fieldset: 'base',
     description: 'Date/time when the event originated. This is the date/time extracted from the event, typically representing when the event was generated by the source. If the event source has no original timestamp, this value is typically populated by the first time the event was received by the pipeline. Required field for all events.',
     name: '@timestamp',
     type: 'date',
   },
   message: {
     fieldset: 'base',
     description: 'For log events the message field contains the log message, optimized for viewing in a log viewer. For structured logs without an original message field, other fields can be concatenated to form a human-readable summary of the event. If multiple messages exist, they can be combined into one message.',
     name: 'message',
     type: 'match_only_text',
   }
 }
